### ISSUE TITLE
Proguard Problem

### ISSUE THREAD

**Issue by el-sh** [boussouira/android-arabic-reader#2]
when proguard is enabled, the apk does not work. It seems proguard.cfg is not ok.
Any idea for this?

**Comment by boussouira** [comment]
What error do you see in the produced apk file?

**Comment by el-sh** [comment]
The application crashes. 
In debug mode, it works well.

**Comment by boussouira** [comment]
Are you using Eclipse to export the release APK?

**Comment by el-sh** [comment]
No. I use ant. 
I think proguard.cfg must be revised.
