### ISSUE TITLE
  "libhoudini.so" not found 

### ISSUE THREAD

**Issue by sijojosep** [boussouira/android-arabic-reader#5]
When build Arabic reader i face  an issue .I am successfully buld the  project and import it into the eclipse.And when run i got an issue

*_##the issue  as follows *_

04-21 09:20:06.873: E/dalvikvm(1412): dlopen("/data/data/net.sourceforge.arabicReader/files/libNativeFormats-v4.so") failed: Cannot load library: load_library(linker.cpp:745): library "/system/lib/libhoudini.so" not found

**## and another one**
04-21 11:50:11.256: E/AndroidRuntime(3420): FATAL EXCEPTION: main
04-21 11:50:11.256: E/AndroidRuntime(3420): Process: net.sourceforge.arabicReader:configService, PID: 3420
04-21 11:50:11.256: E/AndroidRuntime(3420): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "atof" referenced by "libNativeFormats-v4.so"...
04-21 11:50:11.256: E/AndroidRuntime(3420):     at java.lang.Runtime.load(Runtime.java:333)
04-21 11:50:11.256: E/AndroidRuntime(3420):     at java.lang.System.load(System.java:512)
04-21 11:50:11.256: E/AndroidRuntime(3420):     at org.geometerplus.android.util.NativeLibraryUtil.tryLoad(NativeLibraryUtil.java:66)
04-21 11:50:11.256: E/AndroidRuntime(3420):     at org.geometerplus.android.util.NativeLibraryUtil.init(NativeLibraryUtil.java:42)
04-21 11:50:11.256: E/AndroidRuntime(3420):     at org.geometerplus.android.fbreader.FBReaderApplication.onCreate(FBReaderApplication.java:29)
04-21 11:50:11.256: E/AndroidRuntime(3420):     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
04-21 11:50:11.256: E/AndroidRuntime(3420):     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4730)
04-21 11:50:11.256: E/AndroidRuntime(3420):     at android.app.ActivityThread.access$1600(ActivityThread.java:175)
04-21 11:50:11.256: E/AndroidRuntime(3420):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
04-21 11:50:11.256: E/AndroidRuntime(3420):     at android.os.Handler.dispatchMessage(Handler.java:102)
04-21 11:50:11.256: E/AndroidRuntime(3420):     at android.os.Looper.loop(Looper.java:146)
04-21 11:50:11.256: E/AndroidRuntime(3420):     at android.app.ActivityThread.main(ActivityThread.java:5602)
04-21 11:50:11.256: E/AndroidRuntime(3420):     at java.lang.reflect.Method.invokeNative(Native Method)
04-21 11:50:11.256: E/AndroidRuntime(3420):     at java.lang.reflect.Method.invoke(Method.java:515)
04-21 11:50:11.256: E/AndroidRuntime(3420):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
04-21 11:50:11.256: E/AndroidRuntime(3420):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
04-21 11:50:11.256: E/AndroidRuntime(3420):     at dalvik.system.NativeStart.main(Native Method)

**Comment by boussouira** [comment]
Did you build the JNI libraries using the NDK?
