### ISSUE TITLE
Left to Right page sliding

### ISSUE THREAD

**Issue by darwinfrancis** [boussouira/android-arabic-reader#6]
Hi, i want to enable left tot right sliding option for English books and right to left for Arabic books,how can i achieve this function in this project.

**Comment by darwinfrancis** [comment]
Ok.... i found the solution,
You can change the behavior of page turning direction by simply modifying the AnimationProvider class in org.geometerplus.zlibrary.ui.android.view.animation package.

CHANGE

if (getPageToScrollTo() != ZLViewEnums.PageIndex.previous)
 {
    forward = !forward;
 }

TO

if (getPageToScrollTo() == ZLViewEnums.PageIndex.previous)
 {
    forward = !forward;
 }

**Comment by boussouira** [comment]
Take a look at this change: 262df662
